language: python
# ===== Linux =====
os: linux
dist: xenial
python:
  - 3.6
  - 3.7
  - 3.8
  - "3.6-dev"
  - "3.7-dev"
  - "3.8-dev"
  - "3.9-dev"
matrix:
  fast_finish: true
  allow_failures:
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "3.8-dev"
    - python: "3.9-dev"
before_install:
  - pip3 install --upgrade pip
  - pip3 install --upgrade pytest
  - pip3 install codecov
install:
  - pip3 install ".[test]" 
script:
  - pytest
  - codecov
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
