language: python
# ===== Linux =====
os: linux
dist: xenial
python:
  - 3.6
  - 3.7
  - 3.8
before_install:
  - pip3 install --upgrade pip
  - pip3 install --upgrade pytest
  - pip3 install codecov
install:
  - pip3 install ".[test]" 
script:
  - pytest
  - codecov
